# Generated by Django 3.2 on 2024-10-14 05:00


from django.db import migrations

from django.conf import settings
from django.contrib.auth.models import Group, Permission
from django.core.management.sql import emit_post_migrate_signal
from django.db import migrations
import logging


logger = logging.getLogger(__name__)

role_permissions = {
    'Profissional': [
        "solicitacao_agendamento_create",
        "solicitacao_agendamento_list", 
        "solicitacao_agendamento_retrieve",
        "solicitacao_agendamento_update",
        "solicitacao_agendamento_partial_update", 
        "solicitacao_agendamento_destroy",
        "user_list", 
        "user_retrieve",
        "user_update",
        "user_partial_update", 
        "prontuario_create",
        "prontuario_list",
        "prontuario_retrieve",
        "prontuario_update",
        "prontuario_partial_update",
        "prontuario_destroy",
        "profissionalprocedimento_create",
        "profissionalprocedimento_list",
        "profissionalprocedimento_retrieve",
        "profissionalprocedimento_update",
        "profissionalprocedimento_partial_update",
        "profissionalprocedimento_destroy",
        "procedimento_create",
        "procedimento_list",
        "procedimento_retrieve",
        "procedimento_update",
        "procedimento_partial_update",
        "procedimento_destroy",
        "paciente_create",
        "paciente_list",
        "paciente_retrieve",
        "paciente_update",
        "paciente_partial_update",
        "horariosatendimento_create",
        "horariosatendimento_list",
        "horariosatendimento_retrieve",
        "horariosatendimento_update",
        "horariosatendimento_partial_update",
        "horariosatendimento_destroy",
        "endereco_create",
        "endereco_list",
        "endereco_retrieve",
        "endereco_update",
        "endereco_partial_update",
        "endereco_destroy",
        "convenio_create",
        "convenio_list",
        "convenio_retrieve",
        "convenio_update",
        "convenio_partial_update",
        "convenio_destroy",
        
    ],
    'Padrao': [
        "user_partial_update",
        "only_change_own",
        "solicitacao_agendamento_list",
        "solicitacao_agendamento_retrieve",
    ],
}


def add_role_permissions(apps, schema_editor):
    emit_post_migrate_signal(2, False, 'default')

    for r in role_permissions:
        role, created = Group.objects.get_or_create(name=r)
        logger.info(f'{r} Role retrieved')
        for p in role_permissions[r]:
            perm, created2 = Permission.objects.get_or_create(codename=p)
            role.permissions.add(perm)
            logger.info(f'Permitting {r} to {p}')
        role.save()
        
        
class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '__latest__'),
        ('auth', '__latest__'), 
        ('calendar_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_role_permissions),
    ]
