# Generated by Django 3.2 on 2024-09-22 23:17

import calendar_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='nome_social',
        ),
        migrations.RemoveField(
            model_name='profissional',
            name='auto_confirm_atendimento',
        ),
        migrations.RemoveField(
            model_name='solicitacaoagendamento',
            name='confirmacao_paciente',
        ),
        migrations.RemoveField(
            model_name='solicitacaoagendamento',
            name='confirmacao_profissional',
        ),
        migrations.RemoveField(
            model_name='solicitacaoagendamento',
            name='envio_confirmacao_paciente',
        ),
        migrations.RemoveField(
            model_name='solicitacaoagendamento',
            name='hora_fim_consulta',
        ),
        migrations.RemoveField(
            model_name='solicitacaoagendamento',
            name='status',
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(max_length=32, unique=True, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
    ]
