# Generated by Django 3.2 on 2024-10-14 05:51

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0002_create_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convenio',
            options={'managed': True, 'permissions': [('convenio_create', 'Pode criar convênios'), ('convenio_list', 'Pode listar convênios'), ('convenio_retrieve', 'Pode recuperar um convênio'), ('convenio_update', 'Pode atualizar convênios'), ('convenio_partial_update', 'Pode atualizar parcialmente convênios'), ('convenio_destroy', 'Pode destruir convênios')]},
        ),
        migrations.AlterModelOptions(
            name='endereco',
            options={'managed': True, 'permissions': [('endereco_create', 'Pode criar endereços'), ('endereco_list', 'Pode listar endereços'), ('endereco_retrieve', 'Pode recuperar um endereço'), ('endereco_update', 'Pode atualizar endereços'), ('endereco_partial_update', 'Pode atualizar parcialmente endereços'), ('endereco_destroy', 'Pode destruir endereços')]},
        ),
        migrations.AlterModelOptions(
            name='horariosatendimento',
            options={'managed': True, 'permissions': [('horariosatendimento_create', 'Pode criar horários de atendimento'), ('horariosatendimento_list', 'Pode listar horários de atendimento'), ('horariosatendimento_retrieve', 'Pode recuperar um horário de atendimento'), ('horariosatendimento_update', 'Pode atualizar horários de atendimento'), ('horariosatendimento_partial_update', 'Pode atualizar parcialmente horários de atendimento'), ('horariosatendimento_destroy', 'Pode destruir horários de atendimento')]},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'managed': True, 'permissions': [('paciente_create', 'Pode criar pacientes'), ('paciente_list', 'Pode listar pacientes'), ('paciente_retrieve', 'Pode recuperar um paciente'), ('paciente_update', 'Pode atualizar pacientes'), ('paciente_partial_update', 'Pode atualizar parcialmente pacientes'), ('paciente_destroy', 'Pode destruir pacientes')]},
        ),
        migrations.AlterModelOptions(
            name='procedimento',
            options={'managed': True, 'permissions': [('procedimento_create', 'Pode criar procedimentos'), ('procedimento_list', 'Pode listar procedimentos'), ('procedimento_retrieve', 'Pode recuperar um procedimento'), ('procedimento_update', 'Pode atualizar procedimentos'), ('procedimento_partial_update', 'Pode atualizar parcialmente procedimentos'), ('procedimento_destroy', 'Pode destruir procedimentos')]},
        ),
        migrations.AlterModelOptions(
            name='profissional',
            options={'managed': True, 'permissions': [('profissional_create', 'Pode criar profissionais'), ('profissional_list', 'Pode listar profissionais'), ('profissional_retrieve', 'Pode recuperar um profissional'), ('profissional_update', 'Pode atualizar profissionais'), ('profissional_partial_update', 'Pode atualizar parcialmente profissionais'), ('profissional_destroy', 'Pode destruir profissionais')]},
        ),
        migrations.AlterModelOptions(
            name='profissionalprocedimento',
            options={'managed': True, 'permissions': [('profissionalprocedimento_create', 'Pode criar profissional procedimentos'), ('profissionalprocedimento_list', 'Pode listar profissional procedimentos'), ('profissionalprocedimento_retrieve', 'Pode recuperar um profissional procedimento'), ('profissionalprocedimento_update', 'Pode atualizar profissional procedimentos'), ('profissionalprocedimento_partial_update', 'Pode atualizar parcialmente profissional procedimentos'), ('profissionalprocedimento_destroy', 'Pode destruir profissional procedimentos')]},
        ),
        migrations.AlterModelOptions(
            name='prontuario',
            options={'managed': True, 'permissions': [('prontuario_create', 'Pode criar prontuários'), ('prontuario_list', 'Pode listar prontuários'), ('prontuario_retrieve', 'Pode recuperar um prontuário'), ('prontuario_update', 'Pode atualizar prontuários'), ('prontuario_partial_update', 'Pode atualizar parcialmente prontuários'), ('prontuario_destroy', 'Pode destruir prontuários')]},
        ),
        migrations.AlterModelOptions(
            name='solicitacaoagendamento',
            options={'managed': True, 'permissions': [('solicitacao_agendamento_create', 'Pode criar solicitações de agendamento'), ('solicitacao_agendamento_list', 'Pode listar solicitações de agendamento'), ('solicitacao_agendamento_retrieve', 'Pode recuperar uma solicitação de agendamento'), ('solicitacao_agendamento_update', 'Pode atualizar solicitações de agendamento'), ('solicitacao_agendamento_partial_update', 'Pode atualizar parcialmente solicitações de agendamento'), ('solicitacao_agendamento_destroy', 'Pode destruir solicitações de agendamento')]},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True),
        ),
    ]
