# Generated by Django 3.2 on 2024-09-21 13:18

import calendar_api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0002_auto_20240918_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacaoagendamento',
            old_name='envio_confirmacao',
            new_name='envio_confirmacao_paciente',
        ),
        migrations.AlterField(
            model_name='convenio',
            name='inscricao',
            field=models.CharField(max_length=64, validators=[calendar_api.validators.validade_char_lower_than_64]),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='nome',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=8, validators=[calendar_api.validators.validate_cep]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, validators=[calendar_api.validators.validate_state]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(blank=True, null=True, validators=[calendar_api.validators.validate_integer]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='quadra_lote',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[calendar_api.validators.validade_char_lower_than_16]),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='horariosatendimento',
            name='dia_da_semana',
            field=models.CharField(choices=[('2a', 'Segunda-feira'), ('3a', 'Terça-feira'), ('4a', 'Quarta-feira'), ('5a', 'Quinta-feira'), ('6a', 'Sexta-feira'), ('Sab', 'Sábado'), ('Dom', 'Domingo')], max_length=3, validators=[calendar_api.validators.validate_days_of_week]),
        ),
        migrations.AlterField(
            model_name='horariosatendimento',
            name='fim',
            field=models.TimeField(validators=[calendar_api.validators.validate_time_format]),
        ),
        migrations.AlterField(
            model_name='horariosatendimento',
            name='inicio',
            field=models.TimeField(validators=[calendar_api.validators.validate_time_format]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=11, validators=[calendar_api.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='convenio_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_api.convenio'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[calendar_api.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='endereco_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_api.endereco'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(validators=[calendar_api.validators.validate_date_format, calendar_api.validators.validate_date_not_130_years_later, calendar_api.validators.validate_date_not_newer_than_today]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nome_social',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='orgao_expeditor',
            field=models.CharField(max_length=16, validators=[calendar_api.validators.validade_char_lower_than_16]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='rg',
            field=models.CharField(max_length=9, unique=True, validators=[calendar_api.validators.validate_rg]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], max_length=1, validators=[calendar_api.validators.validate_sex]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sobrenome',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[calendar_api.validators.validate_cpf]),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='n_registro',
            field=models.PositiveIntegerField(validators=[calendar_api.validators.validate_integer, calendar_api.validators.validate_grater_than_1]),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='nome',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='sobrenome',
            field=models.CharField(max_length=32, validators=[calendar_api.validators.validade_char_lower_than_32]),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='tipo_registro',
            field=models.CharField(choices=[('CRM', 'Conselho Regional de Medicina'), ('CRBM', 'Conselho Regional de Biomedicina'), ('CRO', 'Conselho Regional de Odontologia'), ('COREN', 'Conselho Regional de Enfermagem'), ('CRF', 'Conselho Regional de Farmácia'), ('CRN', 'Conselho Regional de Nutrição')], max_length=8, validators=[calendar_api.validators.validate_registers]),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='uf_registro',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, validators=[calendar_api.validators.validate_state]),
        ),
        migrations.AlterField(
            model_name='profissionalprocedimento',
            name='tempo_duracao',
            field=models.DurationField(validators=[calendar_api.validators.validate_duration]),
        ),
        migrations.AlterField(
            model_name='solicitacaoagendamento',
            name='data_consulta',
            field=models.DateField(validators=[calendar_api.validators.validate_date_format]),
        ),
        migrations.AlterField(
            model_name='solicitacaoagendamento',
            name='hora_inicio_consulta',
            field=models.TimeField(validators=[calendar_api.validators.validate_time_format]),
        ),
    ]
