# Generated by Django 3.2 on 2024-09-21 13:36

import calendar_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0003_auto_20240921_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='nascimento',
            field=models.DateField(validators=[calendar_api.validators.validate_date_not_130_years_later, calendar_api.validators.validate_date_not_newer_than_today]),
        ),
    ]
