name: main

on:
  push:
    branches: [ "main" ]

jobs:
  test-build:
    name: Build and Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: make build

      - name: Run application in the background
        run: make up

      - name: Check logs for errors
        run: docker-compose logs web

      - name: Run Tests
        run: docker exec -it dz01 python manage.py test -v 0
